### PR TITLE
restructed data structure

### LINKED ISSUE #8: inject scanKey library

### LINKED ISSUE #13: use a new data structure for better separation of concerns
Data structures:
refreshToken: {accessToken, userId}
userId: [refreshToken]

### PR DESCRIPTION
**Pull request by Amri91**
Resolves #13 
Closes #8

### CODE REVIEW

**Comment by Amri91** [comment]
I was too focused on fluturizing the library, so that slipped my mind, I do not think this should be merged like this then. Perhaps I can set a TTL on the whole user set and refresh that TTL whenever a new token is created.

**Comment by Amri91** [comment]
Adding an expiry on a whole set, and refreshing this expiry whenever a new token pair is created for a user id would work.

**Comment by Avaq** [comment]
Ah, that's a great idea! At least dead users will not hang around that way.

**Comment by Amri91** [comment]
Updated the commit

**Pull request merged**
